s = set()
n = input("Enter your language: ")
s.add(str(n))
n = input("Enter your language: ")
s.add(str(n))
n = input("Enter your language: ")
s.add(str(n))
n = input("Enter your language: ")
s.add(str(n))
n = input("Enter your language: ")
s.add(str(n))
n = input("Enter your language: ")
s.add(str(n))
n = input("Enter your language: ")
s.add(str(n))

print(s, type(s))
